### ISSUE TITLE
Kiosc always displays the full log

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/kiosc-server#136]
**Describe the bug**
Kiosc always displays the full log.

**To Reproduce**
1. Start a container that generates logs.
2. Let it run for a long time.
3. See that all lines are loaded.

**Expected behavior**
Make it configurable such that only the last X lines are shown, default to 1k, configurable (through settings/environment variable) hard maximum, deploy with 10k.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by january3** [comment]
Now I can't see any logs at all.

**Comment by stolpeo** [comment]
fixed with #145 (hopefully)
